version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: weatherapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/weatherapp
    ports:
      - "3000:3000"
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"

volumes:
  postgres_data:
